apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-vote
spec:
  releaseName: azure-vote
  chart:
    git: git@github.com:Azure/arc-multi-tenancy-demo.git
    path: charts/azure-voting
    ref: master
  values:
    image: vyta/azure-vote:v1
    title: "Food Vote App"
    value1: Takeout
    value2: Homecooked
    
